api.version: 1.2.0


spring:
  rabbitmq:
    host: 45.114.84.185
    port: 30672
    username: guest
    password: guest
    virtual-host: /true-license
    requested-heartbeat: 30



logging:
  level:
    com:
      business: DEBUG
    org:
      springframework:
        security: debug
        web.server.adapter: debug